# Generated by Django 2.2.6 on 2020-01-16 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='photos')),
                ('description', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('types', models.CharField(choices=[('laptops', 'laptops'), ('accessories', 'accessories'), ('printers', 'printers'), ('phones', 'phones'), ('television', 'television'), ('repairs', 'repairs')], max_length=120)),
                ('datepost', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'ordering': ['-datepost'],
            },
        ),
    ]
